### ISSUE TITLE
Issues with checkout page for opencart 1.5.6.4

### ISSUE THREAD

**Issue by akhilbisht** [Instamojo/Instamojo-OpenCart-1.5#5]
When using opencart "Journal theme" one of the most popular opencart theme, the issue is coming up at the checkout page. When the option "Pay with instamojo" is selected the confirm now button disappears. again when selecting back another option, (for eg: option for "cash on delivery") the confirm now button reappears. 

Note: Journal theme uses "quick checkout" option for checkout page.

**Comment by ashwch** [comment]
@akhilbisht We support Journal theme only in our OpenCart 2.X plugin: https://github.com/Instamojo/Instamojo-OpenCart-2.0 plugin.
