### ISSUE TITLE
How can I add Custom Parameter to the payment request

### ISSUE THREAD

**Issue by poovarasanvasudevan** [Instamojo/Instamojo-OpenCart-1.5#8]
How Can i add custom parameter to payment request for example orderid

**Comment by ashwch** [comment]
@poovarasanvasudevan Custom data is not allowed. Currently order ID is already passed with each request as [`transaction_id`](https://github.com/Instamojo/Instamojo-OpenCart-1.5/blob/master/upload/catalog/controller/payment/instamojo.php#L48).
